language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
  
before_script:
 - chmod +x ./deploy.sh

script: 
- ./deploy.sh

deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: gdg-kl
  version: staging
  no_promote: true
  on: app-engine

branches:
  only:
   - master
   - firebase-hosting
   - app-engine