language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
before_script:
- npm install -g bower polymer-cli firebase-tools
- bower install
script: 
- polymer build
after_success:
- firebase deploy --token $FIREBASE_TOKEN --non-interactive --only hosting
branches:
  only:
    - master