language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
before_script:
- npm install -g bower polymer-cli firebase-tools
- cd functions && bower install && npm install && cd ..
script: 
- cd functions && polymer build && cd ..
after_success:
- if [ "$TRAVIS_BRANCH" = "october-update" ]; then firebase use development; fi
- if [ "$TRAVIS_BRANCH" = "master" ]; then firebase use default; fi
- firebase deploy --token $FIREBASE_TOKEN --non-interactive --only hosting,functions
branches:
  only:
   - master
   - october-update