runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "7d"

handlers:

- url: /cron/.*
  script: home.app

- url: /bower_components
  static_dir: build/unbundled/bower_components
  http_headers:
    Vary: Accept-Encoding   
      
- url: /images
  static_dir: build/unbundled/images

- url: /src
  static_dir: build/unbundled/src
  http_headers:
    Vary: Accept-Encoding  

- url: /data
  static_dir: build/unbundled/data
  http_headers:
    Vary: Accept-Encoding    

- url: /service-worker.js
  static_files: build/unbundled/service-worker.js
  upload: build/unbundled/service-worker.js

- url: /manifest.json
  static_files: build/unbundled/manifest.json
  upload: build/unbundled/manifest.json

- url: /.*
  static_files: build/unbundled/index.html
  upload: build/unbundled/index.html
  http_headers:
    Vary: Accept-Encoding  
  